### ISSUE TITLE
Web socket suddenly disconnects user from the meeting

### ISSUE THREAD

**Issue by Kammann123** [Shawarma-ASSD/spatialmeetings#1]
Sometimes the user stops sending and receiving audio and video data, without being sent back to the home page. From the server's terminal, the server's socket is being notified a disconnection of the user's web socket. I believe that, for some reason, the socket gets disconnected and the server closes the mediasoup transports from the server-side signal routing, which freezes the connection in the client-side.
1. Client application should notice any unexpected disconnection to handle unexpected errors. This may enable a situation of 'reloading the connection...' or 'oops! something went wrong, we're sorry'.
2. ¿Why socket connection gets disconnected? This should be fixed.

**Comment by nicotrozzo** [comment]
Fixed, feel free to reopen if something goes wrong, I didn't have time to try too many edge cases.
